spring:
  datasource:
    url: jdbc:mysql://3.34.116.97:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true